### ISSUE TITLE
大佬问下，secrets.START这个参数要怎么设置？

### ISSUE THREAD

**Issue by tvision08** [pascalhack/Auto-Creat-Ibm-Instance#1]
问下，secrets.START这个参数怎么设置，谢谢啦！

**Comment by 2627500295** [comment]
https://github.com/pascalhack/Auto-Creat-Ibm-Instance/blob/e08e54633e19451124a5cd2ee470ac974e6ca06d/.github/workflows/ibmcloud-cf-php-v2ray.yml#L100-L102

感觉这个就是你想要的

**Comment by tvision08** [comment]
好的，我试试，先谢了！
